---
version: '3.8'
services:
  tenderduty:
    build:
      context: ./tenderduty
    container_name: tenderduty
    ports:
      - "8888:8888"
      - "28686:28686"
    volumes:
      - ./config.yml:/var/lib/tenderduty/config.yml:ro
    restart: unless-stopped
